"""
Django settings for mfmaps_content project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mfmaps_content.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mfmaps_content.context_processors.nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'mfmaps_content.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ['DB_HOST'],
        'PORT': os.environ.get('DB_PORT', '25060'),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}

# Local development only — the production DB lives on a private VPC address
# that is unreachable from outside DigitalOcean. Set USE_SQLITE=True in your
# local .env; never set it on the server.
if os.environ.get('USE_SQLITE', 'False') == 'True':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (blog uploads)
# https://docs.djangoproject.com/en/6.0/topics/files/
#
# Production writes to a DigitalOcean Space over the S3 API. Local dev falls
# back to the filesystem, so you don't need credentials on a laptop -- if
# DO_SPACES_KEY is unset, uploads land in content/media/ and are served by
# Django's dev server.
#
# The bucket is deliberately separate from mfmaps-tiles: tile data is
# machine-generated and gets nuked and re-uploaded routinely, blog photos are
# irreplaceable. Keep them apart.

DO_SPACES_KEY = os.environ.get('DO_SPACES_KEY', '')
DO_SPACES_SECRET = os.environ.get('DO_SPACES_SECRET', '')
DO_SPACES_REGION = os.environ.get('DO_SPACES_REGION', 'sfo3')
DO_SPACES_MEDIA_BUCKET = os.environ.get('DO_SPACES_MEDIA_BUCKET', 'mfmaps-media')
DO_SPACES_ENDPOINT = os.environ.get(
    'DO_SPACES_ENDPOINT',
    f'https://{DO_SPACES_REGION}.digitaloceanspaces.com',
)

# Origin hostname by default. Once the Space has CDN enabled, set
# DO_SPACES_MEDIA_DOMAIN to the .cdn. variant to serve through the edge:
#   mfmaps-media.sfo3.cdn.digitaloceanspaces.com
DO_SPACES_MEDIA_DOMAIN = os.environ.get(
    'DO_SPACES_MEDIA_DOMAIN',
    f'{DO_SPACES_MEDIA_BUCKET}.{DO_SPACES_REGION}.digitaloceanspaces.com',
)

USE_SPACES = bool(DO_SPACES_KEY and DO_SPACES_SECRET)

if USE_SPACES:
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
            'OPTIONS': {
                'bucket_name': DO_SPACES_MEDIA_BUCKET,
                'endpoint_url': DO_SPACES_ENDPOINT,
                'region_name': DO_SPACES_REGION,
                'access_key': DO_SPACES_KEY,
                'secret_key': DO_SPACES_SECRET,
                'custom_domain': DO_SPACES_MEDIA_DOMAIN,
                'default_acl': 'public-read',
                # Public bucket -- no signed URLs. Signing would break CDN
                # caching and expire every image URL ever pasted into a post.
                'querystring_auth': False,
                # Never clobber an existing key; a re-upload gets a suffix.
                'file_overwrite': False,
                'object_parameters': {
                    'CacheControl': 'public, max-age=31536000',
                },
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
    MEDIA_URL = f'https://{DO_SPACES_MEDIA_DOMAIN}/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'


# Behind nginx, so Django only learns the real scheme from this header.
# Safe here because nginx is the only ingress and always sets it -- never
# enable this if anything can reach gunicorn directly.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Without these, admin logins fail CSRF on HTTPS.
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get(
        'CSRF_TRUSTED_ORIGINS',
        'https://mfmaps.com,https://www.mfmaps.com',
    ).split(',') if o
]

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
