# Generated by Django 6.0.5 on 2026-07-31 19:43

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Appears in the URL: /blog/<slug>/. If you change this, add an alias for the old slug or existing links will break.', max_length=100, unique=True, validators=[blog.models.validate_not_reserved])),
                ('intro', models.TextField(blank=True, help_text='Markdown. Shown at the top of this index page.')),
                ('meta_description', models.CharField(blank=True, help_text='Search-result snippet for this index page.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'post type',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/body/%Y/%m/')),
                ('alt', models.CharField(blank=True, help_text='Describe the image for screen readers and search engines.', max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTypeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, validators=[blog.models.validate_not_reserved])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='blog.posttype')),
            ],
            options={
                'verbose_name': 'post type alias',
                'verbose_name_plural': 'post type aliases',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Permanent. Lives at /blog/<slug>/ -- changing it breaks every existing link to this post.', max_length=200, unique=True, validators=[blog.models.validate_not_reserved])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('body', models.TextField(help_text='Markdown.')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for index pages and feeds. Falls back to the opening of the body if left empty.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='blog/hero/%Y/%m/')),
                ('hero_alt', models.CharField(blank=True, help_text='Describe the image for screen readers and search engines.', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='Search-result snippet. Falls back to the excerpt if empty.', max_length=200)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Stamped automatically on first publish. Edit to backdate, or set a future time to schedule.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.posttype')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'permissions': [('view_draft', 'Can view unpublished posts on the live site')],
                'indexes': [models.Index(fields=['status', '-published_at'], name='blog_post_status_615533_idx'), models.Index(fields=['post_type', 'status', '-published_at'], name='blog_post_post_ty_3bea7f_idx')],
            },
        ),
    ]
