# Generated by Django 6.0.5 on 2026-05-13 20:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('species_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('h3_cell_res_8', models.CharField(blank=True, db_index=True, max_length=20)),
                ('h3_cell_res_9', models.CharField(blank=True, db_index=True, max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-created_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='observation_user_id_05e880_idx'), models.Index(fields=['h3_cell_res_8'], name='observation_h3_cell_1b526d_idx'), models.Index(fields=['h3_cell_res_9'], name='observation_h3_cell_f2aff0_idx')],
            },
        ),
    ]
