# Generated by Django 6.0.5 on 2026-05-13 23:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='h3_cell_res_10',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['h3_cell_res_10'], name='observation_h3_cell_cee433_idx'),
        ),
    ]
