# Generated by Django 6.0.5 on 2026-06-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_add_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbodycomment',
            name='click_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterbodycomment',
            name='click_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]